import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Context>
          {children}
        </Context>
      </body>
    </html>
  );
}

const Context = ({children}: any) => {

  return (
    <div className="w-full flex flex-col h-screen">
      <Navbar />
      {children}
    </div>
  )
}


